[package]
name = "aoc"
version = "0.1.0"
authors = ["Péter Budai <buc@peterbudai.eu>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
indoc = "1.0"
itertools = "0.9"
approx = "0.4"
regex = "1.4"
num = "0.3"