[package]
name = "aoc2021"
version = "0.1.0"
authors = ["Péter Budai <buc@peterbudai.eu>"]
edition = "2021"

[lib]
name = "aoc"

[[bin]]
name = "aoc2021"
path = "src/bin.rs"

[dependencies]
anyhow = "1.0"
indoc = "1.0"
itertools = "0.10"
approx = "0.5"
regex = "1.4"
num = "0.4"